### ISSUE TITLE
Small Files

### ISSUE THREAD

**Issue by JimScope** [daxslab/multicp#2]
Has probado hacer un tar de una lista de archivos cuando son pequeños y luego copiarlos. No sería más rápido?

**Comment by glpzzz** [comment]
Tiene sentido y si, normalmente es más rápido con programas como supercopier y otros. Ahora bien, si mal no recuerdo el método usado acá tenía eso en cuenta pues no copia fichero a fichero, sino que crea un paquete del tamaño del buffer y entonces escribe. 

Igual, este proyecto es algo antiguo y estoy abusando de la memoria. Saludos!
-- 
Sent from my Android device with daxSmail.

**Comment by cccaballero** [comment]
En realidad no es objetivo del proyecto, el objetivo es copiar uno o varios ficheros hacia múltiples destinos de la forma mas eficiente posible, ya le correspondería al usuario decidir si archivar o no los ficheros.
En cuanto a si es mas rápido archivar, copiar y luego extraer, no estoy tan seguro, habría que hacer algunas pruebas, la copia del un fichero único por supuesto que es mas rápido, pero el proceso de archivar y extraer los ficheros igual va a demorar su poco, en teoría incluso podría tardar mas.

**Comment by JimScope** [comment]
Ok, gracias por la información
